### ISSUE TITLE
[Question]: Setup Multiple pixel ids

### ISSUE THREAD

**Issue by aeq-dev** [combindma/laravel-facebook-pixel#2]
### What happened?

Hi @omarherri 
Thanks for this awesome package,
Please, how could we manage multiple pixel ids ? 
Thanks

### How to reproduce the bug

-

### Package Version

-

### PHP Version

8.2

### Laravel Version

10.x

**Comment by omarherri** [comment]
At the moment this is not possible. I think i just need to tackle the documentation provided by Facebook to implement this. 
But definitely this is will be added soon.

**Comment by omarherri** [comment]
As for now you can set the Pixel id on the fly using this in your controller:

`FacebookPixel::setPixelId('XXXXXXXX');`

Maybe this is an all-round solution for the moment.
