### ISSUE TITLE
[question]: further UserData in the "head.blade.php"

### ISSUE THREAD

**Issue by DuniPN** [combindma/laravel-facebook-pixel#5]
### What happened?

Hi @omarherri
Thanks for this awesome package,
How can I capture additional UserData (not just "em" and "external_id") in the "head.blade.php"?
I want to send the same UserData via "fbq('init', ...)" that I send via the Conversions API.
Thanks

### How to reproduce the bug

.

### Package Version

4.1.0

### PHP Version

8.1.5

### Laravel Version

10.48.4

### Which operating systems does with happen with?

Windows

**Comment by omarherri** [comment]
Hi,

Actually, I'll be releasing a new version. In this version, you'll be able to add the tag using the new component syntax, allowing everyone to customize it according to their requirements.
